[bitnami/mariadb,mysql,mariadb-galera] Add extraEnvVars support (#2480)
* [bitnami/mariadb,mysql,mariadb-galera] Add extraEnvVars support

* [bitnami/mariadb] Update components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/mysql] Update components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/cassandra] Allow to specify maxUnavailable pods (#2457)

* [bitnami/cassandra] Allow to specify maximumUnavailable pods

* Update values-production.yaml

* Update values.yaml

* Update values.yaml

* Update values-production.yaml

* [bitnami/cassandra] Update components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

Co-authored-by: Carlos Rodríguez Hernández <carlosrh@vmware.com>
Co-authored-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/dokuwiki] Release 6.0.17 updating components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/airflow] add podManagementPolicy support for workers (#2420)

* airflow: add podManagementPolicy support for workers

* [bitnami/airflow]: add podManagementPolicy to values files

* Fix if statement

CI/CD was failing because:
```
Error: parse error at (airflow/templates/statefulset-worker.yaml:12): function “Values” not defined
```

* [bitnami/airflow]: fix incorrect if statement

* Update values-production.yaml

* Update values.yaml

* [bitnami/airflow] Update components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

Co-authored-by: Carlos Rodríguez Hernández <carlosrh@vmware.com>
Co-authored-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/opencart] Release 7.0.15 updating components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/zookeeper] fix() typo (#2481)

* fix() typo

* [bitnami/zookeeper] Update components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

Co-authored-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/fluentd] Release 1.0.5 updating components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/phabricator] Release 9.1.2 updating components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/minio] Release 3.3.8 updating components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/mongodb] add storageClass field for secondary in persistence (#2407)

* [bitnami/mongodb] add storageClass definition for secondaries

* bump mongodb chart version

* [bitnami/mongodb] Update components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

Co-authored-by: Javier J. Salmerón-García <jsalmeron@bitnami.com>
Co-authored-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/rabbitmq] fix extraPorts indentation (#2496)

* fix extraPorts indentation

* bump chart version

* [bitnami/rabbitmq] Update components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

Co-authored-by: Bitnami Containers <containers@bitnami.com>

* [bitnami/redis-cluster] Fix metrics secret volume mount path (#2489)

* Fix metrics secret volume mount path

* Bump chart version

* [bitnami/redis-cluster] Update components versions

Signed-off-by: Bitnami Containers <containers@bitnami.com>

Co-authored-by: Bitnami Containers <containers@bitnami.com>

* Fix Zookeeper Readme (#2486)

* Revert galera

Co-authored-by: Bitnami Containers <containers@bitnami.com>
Co-authored-by: Adam Stankiewicz <sheerun@sher.pl>
Co-authored-by: Carlos Rodríguez Hernández <carlosrh@vmware.com>
Co-authored-by: iamsudip <iamsudip@programmer.net>
Co-authored-by: Onur YALAZI <oyalazi@ptc.com>
Co-authored-by: golgoth31 <golgoth31@users.noreply.github.com>
Co-authored-by: Pierre Chalamet <pierre@chalamet.net>
Co-authored-by: Juliusz Marciniak <juliusz.marciniak+github@gmail.com>
Co-authored-by: Jake Sylvestre <jakesyl@gmail.com>